/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framesgps;


import java.awt.Color;
import java.util.Random;

/**
 *
 * @author ERIK
 */
public class CalculosMatematicos extends javax.swing.JFrame {
    Random rand = new Random();

    /**
     * Creates new form CalculosMatematicos
     */
    Menu men;
    Interact inter = new Interact();
    Player pl = new Player();
    int intent = 0;
    
    boolean flag1 = false;
    boolean flag2 = false;
    boolean flag3 = false;
    boolean flag4 = false;
    boolean flag5 = false;
    
    public CalculosMatematicos() {
        initComponents();
       
        operando1.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando2.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando3.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando4.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando5.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando6.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando7.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando8.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando9.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando10.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        
        Imagen im = new Imagen();
        String menu = "botonMenu.png";
        im.setImageBoton(201,61,menu, botonMenu);
        Color color = new Color(102, 189, 230);
        getContentPane().setBackground(color);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operando1 = new javax.swing.JLabel();
        operador1 = new javax.swing.JLabel();
        operando3 = new javax.swing.JLabel();
        operador2 = new javax.swing.JLabel();
        operando5 = new javax.swing.JLabel();
        operador3 = new javax.swing.JLabel();
        operando7 = new javax.swing.JLabel();
        operador4 = new javax.swing.JLabel();
        operando9 = new javax.swing.JLabel();
        operador5 = new javax.swing.JLabel();
        operando10 = new javax.swing.JLabel();
        operando2 = new javax.swing.JLabel();
        operando4 = new javax.swing.JLabel();
        operando6 = new javax.swing.JLabel();
        operando8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        botonMenu = new javax.swing.JButton();
        BotRevisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        operando1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando1.setText("jLabel1");

        operador1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador1.setText("+");

        operando3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando3.setText("jLabel3");

        operador2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador2.setText("-");

        operando5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando5.setText("jLabel5");

        operador3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador3.setText("+");

        operando7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando7.setText("jLabel7");

        operador4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador4.setText("*");

        operando9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando9.setText("jLabel9");

        operador5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador5.setText("*");

        operando10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando10.setText("jLabel10");

        operando2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando2.setText("jLabel2");

        operando4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando4.setText("jLabel4");

        operando6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando6.setText("jLabel6");

        operando8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando8.setText("jLabel8");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel16.setText("=");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel17.setText("=");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel18.setText("=");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel19.setText("=");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel20.setText("=");

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        botonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuActionPerformed(evt);
            }
        });

        BotRevisar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        BotRevisar.setText("REVISAR");
        BotRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRevisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel1.setText("Intentos: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(operando3)
                                    .addGap(47, 47, 47)
                                    .addComponent(operador2)
                                    .addGap(49, 49, 49)
                                    .addComponent(operando4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(operando5)
                                        .addComponent(operando9))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(operador3)
                                            .addGap(49, 49, 49)
                                            .addComponent(operando6))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(operador5)
                                            .addGap(43, 43, 43)
                                            .addComponent(operando10))))
                                .addComponent(operando8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(operando1)
                                            .addGap(47, 47, 47)
                                            .addComponent(operador1)))
                                    .addGap(49, 49, 49)
                                    .addComponent(operando2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(operando7)
                                .addGap(47, 47, 47)
                                .addComponent(operador4)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotRevisar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(botonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(operando2)
                            .addComponent(jLabel17))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(operando1)
                            .addComponent(operador1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(operando4)
                                .addComponent(jLabel18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(operando3)
                                .addComponent(operador2))))
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(operando6)
                        .addComponent(operador3)
                        .addComponent(operando5)
                        .addComponent(jLabel19)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operando7)
                    .addComponent(operador4)
                    .addComponent(operando8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operando9)
                    .addComponent(operador5)
                    .addComponent(operando10)
                    .addComponent(jLabel16)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotRevisar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void botonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuActionPerformed
        pl.click();
        inter.setRanking("Calculos", intent);
        men = new Menu();
        inter.back(men, this);
    }//GEN-LAST:event_botonMenuActionPerformed

    private void BotRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRevisarActionPerformed
        pl.click();
        if( !jTextField1.getText().equals("") && !jTextField2.getText().equals("") &&
            !jTextField3.getText().equals("") && !jTextField4.getText().equals("") && 
            !jTextField5.getText().equals("")){
            
            if (Integer.parseInt(operando1.getText()) + Integer.parseInt(operando2.getText()) == Integer.parseInt(jTextField1.getText()) ) {
                jTextField1.setBackground(Color.green);
                flag1 = true;
            }
            else{
                jTextField1.setBackground(Color.red);
                flag1 = false;
            }
            if (Integer.parseInt(operando3.getText())- Integer.parseInt(operando4.getText()) == Integer.parseInt(jTextField2.getText()) ) {
                jTextField2.setBackground(Color.green);
                flag2 = true;
            }
            else{
                 jTextField2.setBackground(Color.red);
                 flag2 = false;
            }
            if (Integer.parseInt(operando5.getText()) + Integer.parseInt(operando6.getText()) == Integer.parseInt(jTextField3.getText()) ) {
                jTextField3.setBackground(Color.green);
                flag3 = true;
            }
            else{
                 jTextField3.setBackground(Color.red);
                 flag3 = false;
            }
            if (Integer.parseInt(operando7.getText()) * Integer.parseInt(operando8.getText()) == Integer.parseInt(jTextField4.getText()) ) {
                jTextField4.setBackground(Color.green);
                flag4 = true;
            }
            else{
                 jTextField4.setBackground(Color.red);
                flag4 = false;
            }
            if (Integer.parseInt(operando9.getText()) * Integer.parseInt(operando10.getText()) == Integer.parseInt(jTextField5.getText()) ) {
                jTextField5.setBackground(Color.green);
                flag5 = true;
            }
            else{
                 jTextField5.setBackground(Color.red);
                 flag5 = false;
            }
        }
        else{
            pl.error();
        }
        if(flag1 && flag2 && flag3 && flag4 && flag5){
            pl.victoria();
            this.jTextField1.setEnabled(false);
            this.jTextField2.setEnabled(false);
            this.jTextField3.setEnabled(false);
            this.jTextField4.setEnabled(false);
            this.jTextField5.setEnabled(false);
            this.BotRevisar.setEnabled(false);;
        }
        else{
            pl.error();
            intent++;
            this.jLabel1.setText("Intentos: "+intent);
        }
    }//GEN-LAST:event_BotRevisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculosMatematicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotRevisar;
    private javax.swing.JButton botonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel operador1;
    private javax.swing.JLabel operador2;
    private javax.swing.JLabel operador3;
    private javax.swing.JLabel operador4;
    private javax.swing.JLabel operador5;
    private javax.swing.JLabel operando1;
    private javax.swing.JLabel operando10;
    private javax.swing.JLabel operando2;
    private javax.swing.JLabel operando3;
    private javax.swing.JLabel operando4;
    private javax.swing.JLabel operando5;
    private javax.swing.JLabel operando6;
    private javax.swing.JLabel operando7;
    private javax.swing.JLabel operando8;
    private javax.swing.JLabel operando9;
    // End of variables declaration//GEN-END:variables
}
