/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framesgps;


import java.awt.Color;
import java.util.Random;

/**
 *
 * @author ERIK
 */
public class CalculosMatematicos extends javax.swing.JFrame {
    

    /**
     * Creates new form CalculosMatematicos
     */
    Menu men;
    //creacion de objetos 
    Interact inter = new Interact();
    Player pl = new Player();
    Random rand = new Random();
    Imagen im = new Imagen();
    Color color = new Color(102, 189, 230);
    
    //variable de intentos
    int intent = 0;
    
    //5 banderas inicializadas en falso
    boolean flag1 = false;
    boolean flag2 = false;
    boolean flag3 = false;
    boolean flag4 = false;
    boolean flag5 = false;
    
    public CalculosMatematicos() {
        initComponents();
        //informacion del frame
        this.setLocationRelativeTo(null);
        this.setTitle("Calculos Matematicos");
        im.setIconGeneral(this);
       
        //cada label operando muestra un valor random entre 1 y 10
        operando1.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando2.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando3.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando4.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando5.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando6.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando7.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando8.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando9.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        operando10.setText((rand.nextInt((10 - 1) + 1) + 1)+"");
        
        //mostrar la imegen en el boton correspondiente
        String menu = "BotonMenu.png";
        im.setImageBoton(201,61,menu, botonMenu);
        
        //cambio de color del frame
        getContentPane().setBackground(color);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMenu = new javax.swing.JButton();
        BotRevisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        operando1 = new javax.swing.JLabel();
        operador1 = new javax.swing.JLabel();
        operando2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        operando3 = new javax.swing.JLabel();
        operador2 = new javax.swing.JLabel();
        operando4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        operando5 = new javax.swing.JLabel();
        operador3 = new javax.swing.JLabel();
        operando6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        operando7 = new javax.swing.JLabel();
        operador4 = new javax.swing.JLabel();
        operando8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        operando9 = new javax.swing.JLabel();
        operador5 = new javax.swing.JLabel();
        operando10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(638, 596));

        botonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuActionPerformed(evt);
            }
        });

        BotRevisar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        BotRevisar.setText("REVISAR");
        BotRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRevisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel1.setText("Intentos: ");

        operando1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando1.setText("jLabel1");

        operador1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador1.setText("+");

        operando2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando2.setText("jLabel2");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel17.setText("=");

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operando1)
                .addGap(64, 64, 64)
                .addComponent(operador1)
                .addGap(65, 65, 65)
                .addComponent(operando2)
                .addGap(97, 97, 97)
                .addComponent(jLabel17)
                .addGap(55, 55, 55)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(operando1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(operador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(operando2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        operando3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando3.setText("jLabel3");

        operador2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador2.setText("-");

        operando4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando4.setText("jLabel4");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel18.setText("=");

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operando3)
                .addGap(68, 68, 68)
                .addComponent(operador2)
                .addGap(68, 68, 68)
                .addComponent(operando4)
                .addGap(97, 97, 97)
                .addComponent(jLabel18)
                .addGap(56, 56, 56)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(operando3)
                        .addComponent(operador2)
                        .addComponent(operando4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        operando5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando5.setText("jLabel3");

        operador3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador3.setText("+");

        operando6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando6.setText("jLabel4");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel21.setText("=");

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operando5)
                .addGap(62, 62, 62)
                .addComponent(operador3)
                .addGap(68, 68, 68)
                .addComponent(operando6)
                .addGap(96, 96, 96)
                .addComponent(jLabel21)
                .addGap(58, 58, 58)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(operando5)
                        .addComponent(operador3)
                        .addComponent(operando6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        operando7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando7.setText("jLabel3");

        operador4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador4.setText("*");

        operando8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando8.setText("jLabel4");

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel22.setText("=");

        jTextField4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operando7)
                .addGap(68, 68, 68)
                .addComponent(operador4)
                .addGap(68, 68, 68)
                .addComponent(operando8)
                .addGap(97, 97, 97)
                .addComponent(jLabel22)
                .addGap(56, 56, 56)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(operando7)
                        .addComponent(operador4)
                        .addComponent(operando8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        operando9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando9.setText("jLabel3");

        operador5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operador5.setText("*");

        operando10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        operando10.setText("jLabel4");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel23.setText("=");

        jTextField5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operando9)
                .addGap(68, 68, 68)
                .addComponent(operador5)
                .addGap(68, 68, 68)
                .addComponent(operando10)
                .addGap(97, 97, 97)
                .addComponent(jLabel23)
                .addGap(56, 56, 56)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(operando9)
                        .addComponent(operador5)
                        .addComponent(operando10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285)
                        .addComponent(botonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(BotRevisar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(botonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotRevisar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void botonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuActionPerformed
        //reproduccion del audio click
        pl.click();
        //escribir el nombre y numero de intentos en el archivo de records
        inter.setRanking("Calculos", intent);
        //regresar al menú
        men = new Menu();
        inter.back(men, this);
    }//GEN-LAST:event_botonMenuActionPerformed

    private void BotRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRevisarActionPerformed
        pl.click();
        //verifica que ninguno de los campos de texto sean nulos
        if( !jTextField1.getText().equals("") && !jTextField2.getText().equals("") &&
            !jTextField3.getText().equals("") && !jTextField4.getText().equals("") && 
            !jTextField5.getText().equals("")){
            
            //obtiene los valores los operandos 1 y 2, entonces los suma
            if (Integer.parseInt(operando1.getText()) + Integer.parseInt(operando2.getText()) == Integer.parseInt(jTextField1.getText()) ) {
                //en caso de ser cierto el campo se pinta de verde y la bandera 
                //pasa a true
                jTextField1.setBackground(Color.green);
                flag1 = true;
            }
            else{
                //en caso de ser cierto el campo se pinta de rojo y la bandera 
                //se mantiene en false
                jTextField1.setBackground(Color.red);
                flag1 = false;
            }
            //obtiene los valores los operandos 3 y 4, entonces los suma
            if (Integer.parseInt(operando3.getText())- Integer.parseInt(operando4.getText()) == Integer.parseInt(jTextField2.getText()) ) {
                //en caso de ser cierto el campo se pinta de verde y la bandera 
                //pasa a true
                jTextField2.setBackground(Color.green);
                flag2 = true;
            }
            else{
                //en caso de ser cierto el campo se pinta de rojo y la bandera 
                //se mantiene en false
                 jTextField2.setBackground(Color.red);
                 flag2 = false;
            }
            //obtiene los valores los operandos 5 y 6, entonces los suma
            if (Integer.parseInt(operando5.getText()) + Integer.parseInt(operando6.getText()) == Integer.parseInt(jTextField3.getText()) ) {
                //en caso de ser cierto el campo se pinta de verde y la bandera 
                //pasa a true
                jTextField3.setBackground(Color.green);
                flag3 = true;
            }
            else{
                //en caso de ser cierto el campo se pinta de rojo y la bandera 
                //se mantiene en false
                 jTextField3.setBackground(Color.red);
                 flag3 = false;
            }
            //obtiene los valores los operandos 7 y 8, entonces los suma
            if (Integer.parseInt(operando7.getText()) * Integer.parseInt(operando8.getText()) == Integer.parseInt(jTextField4.getText()) ) {
                //en caso de ser cierto el campo se pinta de verde y la bandera 
                //pasa a true
                jTextField4.setBackground(Color.green);
                flag4 = true;
            }
            else{
                //en caso de ser cierto el campo se pinta de rojo y la bandera 
                //se mantiene en false
                 jTextField4.setBackground(Color.red);
                flag4 = false;
            }
            //obtiene los valores los operandos 9 y 10, entonces los suma
            if (Integer.parseInt(operando9.getText()) * Integer.parseInt(operando10.getText()) == Integer.parseInt(jTextField5.getText()) ) {
                //en caso de ser cierto el campo se pinta de verde y la bandera 
                //pasa a true
                jTextField5.setBackground(Color.green);
                flag5 = true;
            }
            else{
                //en caso de ser cierto el campo se pinta de rojo y la bandera 
                //se mantiene en false
                 jTextField5.setBackground(Color.red);
                 flag5 = false;
            }
        }
        else{
            //sonido de error
            pl.error();
        }
        //si todas las banderas son true 
        if(flag1 && flag2 && flag3 && flag4 && flag5){
            //audio de victoria
            pl.victoria();
            //se desactivan todos los campos el boton de revisar
            this.jTextField1.setEnabled(false);
            this.jTextField2.setEnabled(false);
            this.jTextField3.setEnabled(false);
            this.jTextField4.setEnabled(false);
            this.jTextField5.setEnabled(false);
            this.BotRevisar.setEnabled(false);;
        }
        else{
            //caso de que al menos una sea false
            //audio de error
            pl.error();
            //aumento de contador de intentos y se muestran
            intent++;
            this.jLabel1.setText("Intentos: "+intent);
        }
    }//GEN-LAST:event_BotRevisarActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculosMatematicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotRevisar;
    private javax.swing.JButton botonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel operador1;
    private javax.swing.JLabel operador2;
    private javax.swing.JLabel operador3;
    private javax.swing.JLabel operador4;
    private javax.swing.JLabel operador5;
    private javax.swing.JLabel operando1;
    private javax.swing.JLabel operando10;
    private javax.swing.JLabel operando2;
    private javax.swing.JLabel operando3;
    private javax.swing.JLabel operando4;
    private javax.swing.JLabel operando5;
    private javax.swing.JLabel operando6;
    private javax.swing.JLabel operando7;
    private javax.swing.JLabel operando8;
    private javax.swing.JLabel operando9;
    // End of variables declaration//GEN-END:variables
}
