/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package framesgps;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mgarc
 */
public class MemoriaSensorialOlfativa extends javax.swing.JFrame {

    /**
     * Creates new form MemoriaSensorialOlfativa
     */
    //Se crean los objetos de las clases a usar
    Rand ra = new Rand();
    Menu men;
    Interact inter = new Interact();
    Player pl = new Player();
    Imagen im = new Imagen();
    //Se crean los objetos a usar
    JLabel [] labn = new JLabel[8];
    int [] vals;
    int aciertos = 0;
    int errores = 0;
    
    public MemoriaSensorialOlfativa() {
        initComponents();
        //Se establecen los valores del frame
        this.setLocationRelativeTo(null);   //Centrar
        this.setTitle("Memoria Sensorial Olfativa");    //Titulo
        im.setIconGeneral(this);    //Icono
        
        int[] rand = ra.getNumeros(6);  //Valores entre 1-6 aleatorios
        
        vals = rand;    //Uso global
        
        //Nombres a usar
        String [] noms = {"cafe1.jpg","cebolla.jpg","cigarro.jpg","rosa1.jpg","lavanda.jpg","calcetines.jpg"};
        
        //Botones a usar
        JLabel [] labs = {jLabel1,jLabel2,jLabel3,jLabel4,jLabel5,jLabel6};
        
        labn = labs;    //Uso global
        
        //Se establece la imagen del boton menu
        im.setImageBoton(200, 100, "BotonMenu.png", jButton14);
        
        //Se establecen las imagenes en las etiquetas correspondientes
        im.setIconLabel(rand, noms, labs, 190, 121);
        
        //Se crea el color del fondo
        Color color = new Color(102, 189, 230);
        getContentPane().setBackground(color);  //Se establece el color del fondo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(830, 605));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(220, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 196, 121));

        jButton1.setText("Agradable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, -1, 38));

        jButton2.setText("Desagradable");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 151, -1, 38));

        jPanel2.setPreferredSize(new java.awt.Dimension(220, 200));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 196, 121));

        jButton3.setText("Agradable");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, -1, 38));

        jButton4.setText("Desagradable");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 151, -1, 38));

        jPanel3.setPreferredSize(new java.awt.Dimension(220, 200));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 196, 121));

        jButton5.setText("Agradable");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, -1, 38));

        jButton6.setText("Desagradable");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 151, -1, 38));

        jPanel4.setPreferredSize(new java.awt.Dimension(220, 200));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 196, 121));

        jButton7.setText("Agradable");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, -1, 38));

        jButton8.setText("Desagradable");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 151, -1, 38));

        jPanel5.setPreferredSize(new java.awt.Dimension(220, 200));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 196, 121));

        jButton9.setText("Agradable");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, -1, 38));

        jButton10.setText("Desagradable");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 151, -1, 38));

        jPanel6.setPreferredSize(new java.awt.Dimension(220, 200));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 200, 130));

        jButton11.setText("Agradable");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, 90, 38));

        jButton12.setText("Desagradable");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 38));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Elija el tipo de olor de cada una de las figuras");

        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel8.setText("Errores: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        pl.click(); //Sonido de click
        inter.setRanking("Mem_Sens_Olfativa", errores); //Se guarda el ranking
        men = new Menu();   //Se inicializa menu    
        inter.back(men, this);  //Se abre menu y se cierra el frame actual
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        botonAgr(jLabel1);  //Se verifica el boton de Agradable
        if(!jLabel1.isEnabled()){   //Si el label está deshabilitado
            jButton1.setEnabled(false); //Se deshabilitan sus botones
            jButton2.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        botonDes(jLabel1);  //Se verifica el boton de Desgradable
        if(!jLabel1.isEnabled()){   //Si el label está deshabilitado
            jButton1.setEnabled(false); //Se deshabilitan sus botones
            jButton2.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        botonAgr(jLabel2);  //Se verifica el boton de Agradable
        if(!jLabel2.isEnabled()){   //Si el label está deshabilitado
            jButton3.setEnabled(false); //Se deshabilitan sus botones
            jButton4.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        botonDes(jLabel2);  //Se verifica el boton de Desagradable
        if(!jLabel2.isEnabled()){   //Si el label está deshabilitado
            jButton3.setEnabled(false); //Se deshabilitan sus botones
            jButton4.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        botonAgr(jLabel3);  //Se verifica el boton de Agradable
        if(!jLabel3.isEnabled()){   //Si el label está deshabilitado
            jButton5.setEnabled(false); //Se deshabilitan sus botones
            jButton6.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        botonDes(jLabel3);  //Se verifica el boton de Desagradable
        if(!jLabel3.isEnabled()){   //Si el label está deshabilitado
            jButton5.setEnabled(false); //Se deshabilitan sus botones
            jButton6.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        botonAgr(jLabel4);  //Se verifica el boton de Agradable
        if(!jLabel4.isEnabled()){   //Si el label está deshabilitado
            jButton7.setEnabled(false); //Se deshabilitan sus botones
            jButton8.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        botonDes(jLabel4);  //Se verifica el boton de Desagradable
        if(!jLabel4.isEnabled()){   //Si el label está deshabilitado
            jButton7.setEnabled(false); //Se deshabilitan sus botones
            jButton8.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        botonAgr(jLabel5);  //Se verifica el boton de Agradable
        if(!jLabel5.isEnabled()){   //Si el label está deshabilitado
            jButton9.setEnabled(false); //Se deshabilitan sus botones
            jButton10.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        botonDes(jLabel5);  //Se verifica el boton de Desagradable
        if(!jLabel5.isEnabled()){   //Si el label está deshabilitado
            jButton9.setEnabled(false); //Se deshabilitan sus botones
            jButton10.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        botonAgr(jLabel6);  //Se verifica el boton de Agradable
        if(!jLabel6.isEnabled()){   //Si el label está deshabilitado
            jButton11.setEnabled(false); //Se deshabilitan sus botones
            jButton12.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        botonDes(jLabel6);  //Se verifica el boton de Desagradable
        if(!jLabel6.isEnabled()){   //Si el label está deshabilitado
            jButton11.setEnabled(false); //Se deshabilitan sus botones
            jButton12.setEnabled(false);
        }
        if(aciertos==6){    //Si los aciertos son 6
            pl.victoria();  //Sonido de victoria
            JOptionPane.showMessageDialog(rootPane, "MUY BIEN!!");  //Mensaje
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    //Botón agradable
    public void botonAgr(JLabel loc){
        pl.click(); //Sonido de click
        boolean flag = false;
        //Verifica si el valor se corresponde con un que sea agradable
        switch(vals[inter.getPosLabel(labn, loc)]){
            case 1 : flag = true;
                break;
            case 4 : flag = true;
                break;
            case 5 : flag = true;
                break;
            default: flag = false;
                break;
        }
        if(flag){   //Si lo es
            pl.acierto();   //Sonido de acierto
            loc.setEnabled(false);  //Se deshabilita la etiqueta
            aciertos++;//Acietos aumenta
        }
        else{
            pl.error(); //Sonido de error
            errores++;  //Errroes aumenta
            this.jLabel8.setText("Errores: "+errores);  //Se escriben los errores
        }
    }
    
    //Boton desagradable
    public void botonDes(JLabel loc){
        pl.click(); //Sonido de click
        boolean flag = false;   
        //Verifica si el valor se corresponde con uno que sea desagradable
        switch(vals[inter.getPosLabel(labn, loc)]){
            case 2 : flag = true;
                break;
            case 3 : flag = true;
                break;
            case 6 : flag = true;
                break;
            default: flag = false;
                break;
        }
        if(flag){   //Si lo es
            pl.acierto();   //Sonido de acierto
            loc.setEnabled(false);  //Se deshabilita la etiqueta
            aciertos++;//Acietos aumenta
        }
        else{
            pl.error(); //Sonido de error
            errores++;  //Errroes aumenta
            this.jLabel8.setText("Errores: "+errores);  //Se escriben los errores
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoriaSensorialOlfativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoriaSensorialOlfativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoriaSensorialOlfativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoriaSensorialOlfativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoriaSensorialOlfativa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
